version: "3.3"
services:
  web:
    build: .
    container_name: twitter-viewer
    working_dir: /project
    command: python backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/project

